<a href="https://colab.research.google.com/github/rajanaids-hub/BASICS-ML/blob/main/NaiveBayesAlgorithm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Understanding Naive Bayes Classifiers

Naive Bayes classifiers are a family of simple probabilistic classifiers based on applying Bayes' theorem with strong (naive) independence assumptions between the features. Despite their simplicity, they often perform surprisingly well, especially in text classification and spam filtering.

### The Core Idea: Bayes' Theorem

Bayes' Theorem states:

$$P(A|B) = \frac{P(B|A)P(A)}{P(B)}$$

Where:
- $P(A|B)$ is the posterior probability: the probability of class $A$ given predictor $B$.
- $P(B|A)$ is the likelihood: the probability of predictor $B$ given class $A$.
- $P(A)$ is the prior probability: the probability of class $A$.
- $P(B)$ is the evidence: the probability of predictor $B$.

In the context of classification, we want to find the probability of a class (e.g., 'spam' or 'not spam') given a set of features (e.g., words in an email). So, for a class $y$ and features $x_1, x_2, ..., x_n$:

$$P(y|x_1, ..., x_n) = \frac{P(x_1, ..., x_n|y)P(y)}{P(x_1, ..., x_n)}$$

### The 'Naive' Assumption
The 'naive' part comes from the assumption that all features are independent of each other given the class. This simplifies the likelihood term significantly:

$$P(x_1, ..., x_n|y) = P(x_1|y)P(x_2|y)...P(x_n|y)$$

This makes the calculation feasible, especially for high-dimensional datasets. Now, let's explore the three main types of Naive Bayes classifiers.

---

## 1. Gaussian Naive Bayes

**Use Case**: Gaussian Naive Bayes is typically used when the features are continuous (e.g., height, weight, sensor readings) and are assumed to follow a Gaussian (normal) distribution. If your features are not normally distributed, you might consider transformations to make them so, or use another variant.

**How it Works**: It calculates the mean and standard deviation for each feature within each class. When making a prediction, it uses these parameters to calculate the probability of a given feature value belonging to a class based on its position in the Gaussian distribution curve.

In [1]:
import numpy as np
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# 1. Generate some synthetic data (continuous features)
# Let's imagine we're classifying flowers based on petal length and width
X = np.array([
    [1.1, 0.3], [1.2, 0.4], [1.0, 0.2], [1.3, 0.5], # Class 0: Small flowers
    [4.5, 1.5], [4.7, 1.6], [4.3, 1.4], [4.8, 1.7], # Class 1: Medium flowers
    [6.1, 2.3], [6.0, 2.2], [6.2, 2.4], [6.3, 2.5]  # Class 2: Large flowers
])
y = np.array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2]) # Corresponding classes

print("Generated Data (X, y):")
for i in range(len(X)):
    print(f"Feature: {X[i]}, Class: {y[i]}")

# 2. Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# 3. Initialize and train the Gaussian Naive Bayes model
gnb = GaussianNB()
gnb.fit(X_train, y_train)

# 4. Make predictions on the test set
y_pred = gnb.predict(X_test)

# 5. Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"\nTest Predictions: {y_pred}")
print(f"True Labels:      {y_test}")
print(f"Accuracy: {accuracy:.2f}")

# Example prediction for a new data point
new_flower = np.array([[3.0, 1.0]]) # A new flower with petal length 3.0 and width 1.0
prediction = gnb.predict(new_flower)
print(f"\nPrediction for new flower {new_flower[0]}: Class {prediction[0]}")

Generated Data (X, y):
Feature: [1.1 0.3], Class: 0
Feature: [1.2 0.4], Class: 0
Feature: [1.  0.2], Class: 0
Feature: [1.3 0.5], Class: 0
Feature: [4.5 1.5], Class: 1
Feature: [4.7 1.6], Class: 1
Feature: [4.3 1.4], Class: 1
Feature: [4.8 1.7], Class: 1
Feature: [6.1 2.3], Class: 2
Feature: [6.  2.2], Class: 2
Feature: [6.2 2.4], Class: 2
Feature: [6.3 2.5], Class: 2

Test Predictions: [1 1 0 1]
True Labels:      [2 2 0 2]
Accuracy: 0.25

Prediction for new flower [3. 1.]: Class 1


---

## 2. Multinomial Naive Bayes

**Use Case**: Multinomial Naive Bayes is well-suited for classification with discrete features (e.g., word counts for text classification). It is widely used in natural language processing (NLP) tasks like spam detection, document classification, and sentiment analysis.

**How it Works**: It models the likelihood as a multinomial distribution. For text classification, this means it considers how often each word appears in documents of a certain class. Features are typically integer counts (e.g., how many times a word appears in a document).

In [2]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer

# 1. Sample text data
# Let's imagine classifying emails as 'spam' (1) or 'not spam' (0)
emails = [
    "Free money now! Click this link!",  # Spam
    "Meeting scheduled for tomorrow at 10 AM.", # Not Spam
    "Urgent: Claim your prize!",        # Spam
    "Reminder: Project deadline is Friday.", # Not Spam
    "You've won a lottery!"
]
y_labels = np.array([1, 0, 1, 0, 1]) # Corresponding labels

print("Original Emails and Labels:")
for i, email in enumerate(emails):
    print(f"'{email}' -> Class: {y_labels[i]}")

# 2. Convert text data into a bag-of-words model (feature vectors of word counts)
# CountVectorizer converts text into a matrix of token counts
vectorizer = CountVectorizer()
X_counts = vectorizer.fit_transform(emails)

print("\nFeature Names (Words):", vectorizer.get_feature_names_out())
print("Word Count Matrix (Features for Naive Bayes):\n", X_counts.toarray())

# 3. Split data (optional for small datasets, but good practice)
X_train_counts, X_test_counts, y_train_mnb, y_test_mnb = train_test_split(X_counts, y_labels, test_size=0.4, random_state=42)

# 4. Initialize and train the Multinomial Naive Bayes model
mnb = MultinomialNB()
mnb.fit(X_train_counts, y_train_mnb)

# 5. Make predictions
y_pred_mnb = mnb.predict(X_test_counts)

# 6. Evaluate the model
accuracy_mnb = accuracy_score(y_test_mnb, y_pred_mnb)
print(f"\nTest Predictions: {y_pred_mnb}")
print(f"True Labels:      {y_test_mnb}")
print(f"Accuracy: {accuracy_mnb:.2f}")

# Example prediction for a new email
new_email = ["Claim your free offer today!"]
new_email_counts = vectorizer.transform(new_email)
prediction_mnb = mnb.predict(new_email_counts)
print(f"\nPrediction for new email: '{new_email[0]}' -> Class {prediction_mnb[0]}")

Original Emails and Labels:
'Free money now! Click this link!' -> Class: 1
'Meeting scheduled for tomorrow at 10 AM.' -> Class: 0
'Urgent: Claim your prize!' -> Class: 1
'Reminder: Project deadline is Friday.' -> Class: 0
'You've won a lottery!' -> Class: 1

Feature Names (Words): ['10' 'am' 'at' 'claim' 'click' 'deadline' 'for' 'free' 'friday' 'is'
 'link' 'lottery' 'meeting' 'money' 'now' 'prize' 'project' 'reminder'
 'scheduled' 'this' 'tomorrow' 'urgent' 've' 'won' 'you' 'your']
Word Count Matrix (Features for Naive Bayes):
 [[0 0 0 0 1 0 0 1 0 0 1 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0]
 [1 1 1 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1]
 [0 0 0 0 0 1 0 0 1 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1 1 0]]

Test Predictions: [0 1]
True Labels:      [0 1]
Accuracy: 1.00

Prediction for new email: 'Claim your free offer today!' -> Class 1


---

## 3. Bernoulli Naive Bayes

**Use Case**: Bernoulli Naive Bayes is designed for binary features. This means each feature should represent the presence or absence of something (e.g., a word is present or not in a document, a user clicked or not). It's often used when you care more about *whether* a feature exists than *how many times* it exists.

**How it Works**: It models the likelihood of a feature being present given a class. It expects binary feature vectors (0s and 1s), where 1 means the feature is present and 0 means it's absent. Unlike Multinomial NB, if a feature is absent, it explicitly takes this into account in its probability calculation.

In [3]:
from sklearn.naive_bayes import BernoulliNB

# 1. Sample binary data
# Let's imagine classifying customers as 'will buy' (1) or 'won't buy' (0)
# Features could be: [saw_ad, clicked_ad, visited_website]
X_binary = np.array([
    [1, 1, 1], # Saw ad, clicked, visited -> Will buy
    [1, 0, 1], # Saw ad, didn't click, visited -> Will buy
    [0, 0, 0], # Didn't see ad, didn't click, didn't visit -> Won't buy
    [1, 0, 0], # Saw ad, didn't click, didn't visit -> Won't buy
    [0, 1, 1], # Didn't see ad, clicked, visited -> Will buy (unlikely, but for example)
    [1, 1, 0]  # Saw ad, clicked, didn't visit -> Won't buy
])
y_binary = np.array([1, 1, 0, 0, 1, 0]) # Corresponding labels

print("Generated Binary Data (X, y):")
for i in range(len(X_binary)):
    print(f"Features: {X_binary[i]}, Class: {y_binary[i]}")

# 2. Split data
X_train_bnb, X_test_bnb, y_train_bnb, y_test_bnb = train_test_split(X_binary, y_binary, test_size=0.5, random_state=42)

# 3. Initialize and train the Bernoulli Naive Bayes model
bnb = BernoulliNB()
bnb.fit(X_train_bnb, y_train_bnb)

# 4. Make predictions
y_pred_bnb = bnb.predict(X_test_bnb)

# 5. Evaluate the model
accuracy_bnb = accuracy_score(y_test_bnb, y_pred_bnb)
print(f"\nTest Predictions: {y_pred_bnb}")
print(f"True Labels:      {y_test_bnb}")
print(f"Accuracy: {accuracy_bnb:.2f}")

# Example prediction for a new customer
new_customer = np.array([[1, 0, 1]]) # Saw ad, didn't click, visited website
prediction_bnb = bnb.predict(new_customer)
print(f"\nPrediction for new customer {new_customer[0]}: Class {prediction_bnb[0]}")

Generated Binary Data (X, y):
Features: [1 1 1], Class: 1
Features: [1 0 1], Class: 1
Features: [0 0 0], Class: 0
Features: [1 0 0], Class: 0
Features: [0 1 1], Class: 1
Features: [1 1 0], Class: 0

Test Predictions: [1 0 0]
True Labels:      [1 1 0]
Accuracy: 0.67

Prediction for new customer [1 0 1]: Class 0


---

## Summary and Comparison

| Classifier        | Data Type                 | Feature Representation      | Key Assumption                      | Common Use Cases                               |
|-------------------|---------------------------|-----------------------------|-------------------------------------|------------------------------------------------|
| **Gaussian NB**   | Continuous                | Assumed normal distribution | Features are normally distributed   | Medical diagnosis, real-valued data            |
| **Multinomial NB**| Discrete (counts)         | Integer counts              | Features are word counts/frequencies| Text classification, spam filtering            |
| **Bernoulli NB**  | Binary (presence/absence) | Binary (0s and 1s)          | Features are Boolean                | Text classification (presence of words), feature existence detection |


Each variant of Naive Bayes is designed for different types of feature distributions. Choosing the right one depends on the nature of your input data. Despite the 'naive' independence assumption, these classifiers are computationally efficient, require less training data, and often provide competitive baseline performance, especially in text-related tasks.