<a href="https://colab.research.google.com/github/rajanaids-hub/BASICS-ML/blob/main/NaiveBayes_Types.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Naive Bayes Classifiers: Gaussian, Multinomial, and Bernoulli

Naive Bayes classifiers are a family of simple probabilistic classifiers based on applying Bayes' theorem with strong (naive) independence assumptions between the features. Despite their simplicity, they often perform well in many real-world scenarios, especially with text classification and medical diagnosis.

There are three main types of Naive Bayes classifiers, distinguished by the distribution assumed for the features:

1.  **Gaussian Naive Bayes:** Assumes features follow a Gaussian (normal) distribution.
2.  **Multinomial Naive Bayes:** Suitable for features representing counts (e.g., word counts in text).
3.  **Bernoulli Naive Bayes:** Designed for binary/boolean features (e.g., presence or absence of a word).

### 1. Setup and Data Generation

First, let's import the necessary libraries and create a synthetic dataset that we can use to demonstrate all three types of Naive Bayes classifiers. We'll generate a dataset with some numerical features for Gaussian Naive Bayes, and then transform it for Multinomial and Bernoulli.

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB
from sklearn.metrics import accuracy_score, classification_report
from sklearn.preprocessing import Binarizer

# Generate a synthetic dataset
np.random.seed(42)
X = np.random.rand(200, 5) * 10 # 200 samples, 5 features, values between 0-10
# Create a target variable based on a simple rule to make it linearly separable to some extent
y = ((X[:, 0] + X[:, 1] > 10) + (X[:, 2] < 5)).astype(int)

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

print(f"Original X shape: {X.shape}")
print(f"X_train shape: {X_train.shape}, y_train shape: {y_train.shape}")
print(f"X_test shape: {X_test.shape}, y_test shape: {y_test.shape}")
print("\nFirst 5 rows of X_train:")
print(X_train[:5])
print("\nFirst 5 values of y_train:")
print(y_train[:5])

Original X shape: (200, 5)
X_train shape: (140, 5), y_train shape: (140,)
X_test shape: (60, 5), y_test shape: (60,)

First 5 rows of X_train:
[[4.14624124 0.85349668 9.96874252 5.0219501  5.95385017]
 [9.0115801  0.4544638  2.8096319  9.50411484 8.90263784]
 [2.42055272 6.72135547 7.61619615 2.37637544 7.28216349]
 [3.8867729  2.71349032 8.28737509 3.56753327 2.8093451 ]
 [1.74366429 6.90937738 3.86735346 9.36729989 1.37520944]]

First 5 values of y_train:
[0 1 0 0 1]


### 2. Gaussian Naive Bayes

**Gaussian Naive Bayes** is used when features are continuous and are assumed to follow a Gaussian (normal) distribution. It calculates the mean and standard deviation of each feature for each class during training.

In [2]:
# Initialize and train the Gaussian Naive Bayes model
gnb = GaussianNB()
gnb.fit(X_train, y_train)

# Make predictions on the test set
y_pred_gnb = gnb.predict(X_test)

# Evaluate the model
print("Gaussian Naive Bayes Performance:")
print(f"Accuracy: {accuracy_score(y_test, y_pred_gnb):.4f}")
print("Classification Report:")
print(classification_report(y_test, y_pred_gnb))

Gaussian Naive Bayes Performance:
Accuracy: 0.8000
Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.33      0.50        18
           1       0.78      1.00      0.88        42

    accuracy                           0.80        60
   macro avg       0.89      0.67      0.69        60
weighted avg       0.84      0.80      0.76        60



### 3. Multinomial Naive Bayes

**Multinomial Naive Bayes** is suitable for classification with discrete features (e.g., word counts in text classification). It is typically used for data where feature values represent frequencies or counts. The features should be non-negative. For our synthetic data, we will convert the continuous features to counts or frequencies by rounding and ensuring they are non-negative integers.

In [3]:
# For Multinomial Naive Bayes, features should typically be counts or frequencies.
# Let's convert our continuous features to non-negative integers (e.g., by rounding)
X_train_mnb = np.round(X_train).astype(int)
X_test_mnb = np.round(X_test).astype(int)

# Ensure all features are non-negative
X_train_mnb[X_train_mnb < 0] = 0
X_test_mnb[X_test_mnb < 0] = 0

# Initialize and train the Multinomial Naive Bayes model
mnb = MultinomialNB()
mnb.fit(X_train_mnb, y_train)

# Make predictions on the test set
y_pred_mnb = mnb.predict(X_test_mnb)

# Evaluate the model
print("Multinomial Naive Bayes Performance:")
print(f"Accuracy: {accuracy_score(y_test, y_pred_mnb):.4f}")
print("Classification Report:")
print(classification_report(y_test, y_pred_mnb))

Multinomial Naive Bayes Performance:
Accuracy: 0.8500
Classification Report:
              precision    recall  f1-score   support

           0       0.85      0.61      0.71        18
           1       0.85      0.95      0.90        42

    accuracy                           0.85        60
   macro avg       0.85      0.78      0.80        60
weighted avg       0.85      0.85      0.84        60



### 4. Bernoulli Naive Bayes

**Bernoulli Naive Bayes** is designed for binary or boolean features. It assumes that all features are independent and are Bernoulli distributed, meaning each feature is either present (1) or absent (0). For our synthetic data, we will binarize the features based on a threshold.

In [4]:
# For Bernoulli Naive Bayes, features should be binary (0 or 1).
# We'll use a Binarizer to convert our features.
# Let's say a feature is 'present' if its value is above the mean of all features.

binarizer = Binarizer(threshold=np.mean(X_train))
X_train_bnb = binarizer.fit_transform(X_train)
X_test_bnb = binarizer.transform(X_test)

# Initialize and train the Bernoulli Naive Bayes model
bnb = BernoulliNB()
bnb.fit(X_train_bnb, y_train)

# Make predictions on the test set
y_pred_bnb = bnb.predict(X_test_bnb)

# Evaluate the model
print("Bernoulli Naive Bayes Performance:")
print(f"Accuracy: {accuracy_score(y_test, y_pred_bnb):.4f}")
print("Classification Report:")
print(classification_report(y_test, y_pred_bnb))

Bernoulli Naive Bayes Performance:
Accuracy: 0.7333
Classification Report:
              precision    recall  f1-score   support

           0       0.58      0.39      0.47        18
           1       0.77      0.88      0.82        42

    accuracy                           0.73        60
   macro avg       0.68      0.63      0.64        60
weighted avg       0.71      0.73      0.72        60



### 5. Conclusion

This demonstration illustrates how to implement and use Gaussian, Multinomial, and Bernoulli Naive Bayes classifiers in Python using `scikit-learn`. The choice of which Naive Bayes classifier to use depends heavily on the nature of your features:

*   **Gaussian Naive Bayes** for continuous, normally distributed features.
*   **Multinomial Naive Bayes** for discrete features representing counts or frequencies (e.g., text data).
*   **Bernoulli Naive Bayes** for binary/boolean features (presence or absence).

Even with simple synthetic data, you can observe differences in their performance based on how the data is prepared and which underlying assumptions best fit the feature distribution.